### ISSUE TITLE
Allow other apps to start MainActivity so they can use intent to record audio

### ISSUE THREAD

**Issue by naXa777** [naXa777/SoundRecorder#38]
Android docs: https://d.android.com/training/basics/intents/filters

Example of invoking code:

    Intent intent = new Intent(MediaStore.Audio.Media.RECORD_SOUND_ACTION);
    startActivityForResult(intent, RECORD_REQUEST);

Preconditions:

* there is an app on user's device that needs to record sound, but does not implement this feature itself. so it creates an intent to launch default sound recorder.

Expected behaviour:

* Simple Sound Recorder app appears in Send To list
* when recording is finished it's passed back to the app that created the intent.

**Comment by aman0408** [comment]
Can I work on this?

**Comment by naXa777** [comment]
@aman0408 yes, sure. you're welcome here =)

Sony's audio recorder already has this feature ->
https://play.google.com/store/apps/details?id=com.sonymobile.androidapp.audiorecorder
we can use it as a reference.

**Comment by aman0408** [comment]
I am unable to build the app. Android studio gives me the following error "ERROR: Could not get unknown property 'soundrecorderCrashlyticsApiSecret' for project ':app' of type org.gradle.api.Project."
Could you please guide me on how to go about it?

**Comment by naXa777** [comment]
@aman0408 did you follow steps in Building section?
https://github.com/naXa777/SoundRecorder#building

**Comment by aman0408** [comment]
My bad. I'll do that.

**Comment by aman0408** [comment]
Do you know a way in which I can test it? Any app that requests for an audio recorder app?

**Comment by aman0408** [comment]
I have made a PR. Please look into it.
