### ISSUE TITLE
bug: when stopped from notification bar chronometer and progress bar still goes on  

### ISSUE THREAD

**Issue by mohiuddinify** [naXa777/SoundRecorder#43]
when recording stopped from the notification bar chronometer and progress bar still goes on

**Comment by naXa777** [comment]
please provide more details:

* App version
* Device model
* Android version
* Steps to reproduce the bug
* Expected behaviour
* Actual behaviour (a screenshot, screencast, and/or log file may be helpful)

**Comment by naXa777** [comment]
@mohiuddinify
closing tickets with no response from the author
