### ISSUE TITLE
when clicked on share button crashes the application 

### ISSUE THREAD

**Issue by mohiuddinify** [naXa777/SoundRecorder#44]
when i share a recorded file from within the app, app crashes

**Comment by naXa777** [comment]
please provide more details:

* App version
* Device model
* Android version
* Steps to reproduce the bug
* Expected behaviour
* Actual behaviour (a screenshot, screencast, and/or log file may be helpful)

**Comment by mohiuddinify** [comment]
versionName "2.0.2" 
samsung S7 , sony xz1 
both on Oreo 8.0
* open the application 
* Record a audio 
* go to save recording 
* long click on a recording 
* click share 
Expected behaviour is app should shares the selected item 
app crashes with open app again message..
here are the screen shots
![sketch-1552995513276](https://user-images.githubusercontent.com/48280805/54603651-afea5380-4a66-11e9-9498-36dd5e6fc929.png)
![Screenshot_20190319-163619](https://user-images.githubusercontent.com/48280805/54603665-bbd61580-4a66-11e9-98ed-161f3fbc29b2.png)
