### ISSUE TITLE
Hidden voice recorder

### ISSUE THREAD

**Issue by jony0008** [naXa777/SoundRecorder#47]
I am searching for an open source hidden voice recorder but I think there aren't any. It would be great if this function would be added to this project.

**Comment by har2008preet** [comment]
@naXa777 Can I take this feature?

**Comment by naXa777** [comment]
@har2008preet, yes sure! please take it

**Comment by RenatoViana01** [comment]
is this still open?

**Comment by naXa777** [comment]
@RenatoViana01 yes

**Comment by RenatoViana01** [comment]
I'll pick it up

**Comment by naXa777** [comment]
let's keep the app simple.
