### ISSUE TITLE
app  data clear doesnt work 

### ISSUE THREAD

**Issue by mohiuddinify** [naXa777/SoundRecorder#48]
i was testing the app and when i cleared the data from application management and went back to the application directory the recordings weren't deleted
Android 8.0 oreo  
Sony XZ1 (G8341)

**Comment by naXa777** [comment]
It's by design. We don't want users to accidentally lose their recordings.

**Comment by naXa777** [comment]
@mohiuddinify
closing tickets with no response from the author
