### ISSUE TITLE
[Feature Request] Add menu icon to record list item

### ISSUE THREAD

**Issue by Jantzilla** [naXa777/SoundRecorder#50]
It could be helpful to include a menu icon in the list item layout to more clearly illustrate how to "Share", "Rename", or "Delete" the file.

I would be happy to add this feature.

**Original**

![sound-recorder-original](https://user-images.githubusercontent.com/35611020/55933348-a5008a00-5bf2-11e9-9fa1-f50a65a0bff9.png)

**Change**

![sound-recorder-change](https://user-images.githubusercontent.com/35611020/55933381-bba6e100-5bf2-11e9-80eb-5765f3fc660e.png)

**Comment by naXa777** [comment]
Thank you for your contribution!
Good idea. Feel free to take this issue.

**Comment by Jantzilla** [comment]
It looks like the check has failed for the missing API Key. Let me know if any changes are necessary @naXa777 .

**Comment by naXa777** [comment]
> It looks like the check has failed for the missing API Key

Yes, you're right! Nice work :)
