### ISSUE TITLE
[Unexpected Behavior] Player opens over options on list item "mid length press"

### ISSUE THREAD

**Issue by Jantzilla** [naXa777/SoundRecorder#51]
![sound-recorder-bug](https://user-images.githubusercontent.com/35611020/55933918-8a2f1500-5bf4-11e9-808d-f1d8edce9ffb.png)

**Comment by mohiuddinify** [comment]
i think adding this line of code wil solve this issue 
ADD THIS FILE IN FILE VIEWERADAPTTER in holder.cardview.setonclicklistner

line:                    holder.cardView.cancelLongPress();

**Comment by Jantzilla** [comment]
> ADD THIS IN FILEVIEWERADAPTTER in holder.cardview.setonclicklistner
> 
> line: holder.cardView.cancelLongPress();

I am currently testing. Have you implemented this successfully?

**Comment by Jantzilla** [comment]
It seems that returning `true` from `presentFileOptions(@NonNull final RecordingsViewHolder holder)` instead of `false` solves this problem.
